---
services:
  twingate_connector:
    container_name: ${HOSTNAME}
    restart: unless-stopped
    image: "twingate/connector:latest"
    network_mode: "host"
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - TWINGATE_API_ENDPOINT=/connector.stock
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_LEVEL=3
      - TWINGATE_LOG_ANALYTICS=v2
    labels:
      - "com.watchtower.enable=true"
